### ISSUE TITLE
/eval link in Readme is broke

### ISSUE THREAD

**Issue by mikey60** [allenporter/home-assistant-datasets#15]
Great Project!  Just to let you know about the broken link.  "See the [evals/](https://github.com/allenporter/home-assistant-datasets/blob/main/evals/README.md) directory for more information on running the evaluation."

**Comment by allenporter** [comment]
I updated some of the documentation and now https://github.com/allenporter/home-assistant-datasets/tree/main/datasets/assist is probably the best place for more information on how to run an evaluation.  Thanks for the interest and report and happy to collaborate on anything.
