### ISSUE TITLE
Add evaluation qwen2.5 LLM

### ISSUE THREAD

**Issue by xiasi0** [allenporter/home-assistant-datasets#43]
I performed very well in the Chinese environment (the test was not professional), and I hope you can add a complete evaluation of the English environment. thank you

**Comment by tannisroot** [comment]
I've performed my own evaluation here
https://github.com/tannisroot/home-assistant-datasets/blob/qwen2.5/reports/README.md

**Comment by xiasi0** [comment]
@tannisroot
I was really surprised to see your evaluation results. I didn't expect it to perform well in an English environment. Just like Llama3.1, Chinese support is not user-friendly and almost unusable. This saved me a lot of OpenAI tokens. thank you！
